variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - build_docker
  - build_and_test
  - deploy

build_docker_image:
  stage: build_docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --no-cache -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    changes:
      - Dockerfile

build_and_test:
  stage: build_and_test
  image: $IMAGE_TAG
  script:
    - mkdir build
    - cd build
    - cmake -DDPDK_BACKEND=ON -DAF_PACKET_BACKEND=ON ..
    - make
    - cd ../tests
    - python3 ./run_tests.py -p ../build/dns-probe-af

pages:
  stage: deploy
  image: $IMAGE_TAG
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make doc
    - mv doc/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master
