find_package(PkgConfig REQUIRED)

set(OLD_PKGCFG_ENV $ENV{PKG_CONFIG_PATH})
unset(ENV{PKG_CONFIG_PATH})

foreach(PATH IN LISTS CMAKE_SYSTEM_PREFIX_PATH CMAKE_PREFIX_PATH)
    set(ENV{PKG_CONFIG_PATH} "${PATH}/lib/pkgconfig:$ENV{PKG_CONFIG_PATH}")
endforeach()

set(ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH}:${OLD_PKGCFG_ENV}")
pkg_search_module(LIBYANGCPP libyang-cpp)
set(ENV{PKG_CONFIG_PATH} "${OLD_PKGCFG_ENV}")

find_package_handle_standard_args(LibYang DEFAULT_MSG LIBYANGCPP_FOUND)

if (LIBYANGCPP_FOUND)
    add_library(LibYang::LibYangCpp INTERFACE IMPORTED)
    set_property(TARGET LibYang::LibYangCpp PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${LIBYANGCPP_INCLUDE_DIRS})
    set_property(TARGET LibYang::LibYangCpp PROPERTY INTERFACE_LINK_LIBRARIES ${LIBYANGCPP_LIBRARIES})
    set_property(TARGET LibYang::LibYangCpp PROPERTY INTERFACE_COMPILE_DEFINITIONS ${LIBYANGCPP_DEFINITIONS})
    set_property(TARGET LibYang::LibYangCpp PROPERTY INTERFACE_COMPILE_OPTIONS ${LIBYANGCPP_CFLAGS})
endif()
