find_package(PkgConfig REQUIRED)

set(OLD_PKGCFG_ENV $ENV{PKG_CONFIG_PATH})
unset(ENV{PKG_CONFIG_PATH})

foreach(PATH IN LISTS CMAKE_SYSTEM_PREFIX_PATH CMAKE_PREFIX_PATH)
    set(ENV{PKG_CONFIG_PATH} "${PATH}/lib/pkgconfig:$ENV{PKG_CONFIG_PATH}")
endforeach()

set(ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH}:${OLD_PKGCFG_ENV}")
pkg_search_module(SYSREPOCPP sysrepo-cpp)
set(ENV{PKG_CONFIG_PATH} "${OLD_PKGCFG_ENV}")

find_package_handle_standard_args(Sysrepo DEFAULT_MSG SYSREPOCPP_FOUND)

if (SYSREPOCPP_FOUND)
    add_library(Sysrepo::SysrepoCpp INTERFACE IMPORTED)
    set_property(TARGET Sysrepo::SysrepoCpp PROPERTY INTERFACE_INCLUDE_DIRECTOIRES ${SYSREPOCPP_INCLUDE_DIR})
    set_property(TARGET Sysrepo::SysrepoCpp PROPERTY INTERFACE_LINK_LIBRARIES ${SYSREPOCPP_LIBRARIES})
    set_property(TARGET Sysrepo::SysrepoCpp PROPERTY INTERFACE_COMPILE_DEFINITIONS ${SYSREPOCPP_DEFINITIONS})
    set_property(TARGET Sysrepo::SysrepoCpp PROPERTY INTERFACE_COMPILE_OPTIONS ${SYSREPOCPP_CFLAGS})
endif()
